language: python
python:
    - "3.7"
install:
    - pip install -r requirements-dev.txt
script:
    - pytest
branches:
    only:
        - master
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
